export function smartPrompt(task) {
  return `You are the tiny relevance classifier for 3Things, a coding micro-learning companion.\n\nDecide whether this coding task contains a worthwhile software-engineering learning opportunity.\n\nLaunch for meaningful implementation, debugging, architecture, framework behavior, tooling, testing, security, performance, data, API, deployment, or design-system tasks.\nSkip truly trivial work such as typo-only edits, mechanical renames, obvious text changes, or tiny formatting changes with no useful concept behind them.\n\nTASK:\n${task.prompt}\n\nBe conservative about skipping: if a useful concept can be taught from the task, launch. Keep reason under 12 words.`;
}

export function areasPrompt(task, config) {
  return `You power 3Things, a micro-learning companion for software developers.\n\nThe developer is doing this real task:\n${task.prompt}\n\nTheir configured learning interests are:\n${config.interests.join(', ') || '(none)'}\n\nReturn 3 to 6 learning-area options for this task. Prefer relevant configured interests. If suggestOutsideInterests=${config.suggestOutsideInterests}, add up to 2 highly relevant areas outside the configured list when they would teach something valuable.\n\nFor each option:\n- name: short category such as Backend, Frontend, Security, Architecture, DevOps, Databases, Testing, Performance, AI, Networking, Payments\n- source: "configured" if it matches a configured interest, otherwise "suggested"\n- reason: maximum 8 words, specific to this task\n\nDo not invent irrelevant areas just to fill the list.`;
}

export function topicsPrompt(task, area, historyTitles) {
  const learned = historyTitles.length ? historyTitles.join('; ') : '(none yet)';
  return `You power 3Things, which teaches exactly three compact concepts from a developer's current coding task.\n\nCURRENT TASK:\n${task.prompt}\n\nSELECTED LEARNING AREA: ${area}\n\nRECENTLY LEARNED TOPICS (do not repeat titles or near-duplicates):\n${learned}\n\nThe developer already understands the task they asked for. Do NOT teach the implementation plan, feature requirement, UI copy, variable names, state fields, or obvious mechanics of this exact change.\n\nUse the task only as a clue for the learning context. Return exactly 3 concepts in ${area} that are:\n- non-obvious to a working developer\n- transferable to future projects\n- directly useful while thinking about this task\n- different from recently learned topics\n\nPrefer deep frontend/backend/architecture/testing ideas such as interaction design principles, cognitive load, terminal UX patterns, persistence tradeoffs, failure modes, protocol/framework mechanics, production debugging, accessibility, latency, security, reliability, or maintainability.\n\nReject shallow topics like "Prompt Cooldown State", "Selection Freshness Window", "Notice Before Reconfiguration", or anything that merely restates the requested feature.\n\nEach item needs:\n- title: <= 6 words, name the transferable concept\n- why: <= 14 words, explain the interesting value, not the implementation step.`;
}

export function lessonPrompt(task, area, topics) {
  return `You are 3Things, a compact software-engineering teacher attached to real coding work.\n\nTASK THE DEVELOPER IS CURRENTLY DOING:\n${task.prompt}\n\nLEARNING AREA: ${area}\n\nTEACH THESE TOPICS:\n${topics.map((t, i) => `${i + 1}. ${t.title} — ${t.why}`).join('\n')}\n\nCreate a compact but complete lesson for the selected topic(s). This is micro-learning, not a blog post.\n\nFor EACH topic use exactly these sections:\n# <topic>\n**Mental model** — 2-4 short sentences.\n**How it works** — concise bullets or a tiny ASCII flow when useful.\n**In this task** — connect the knowledge concretely to the task above.\n**Common mistake** — one high-value failure mode.\n**Remember** — one memorable sentence.\n\nRules:\n- Prioritize understanding over code.\n- Teach the transferable concept, not the steps for this exact change.\n- Make the lesson valuable even if the developer already knows the requested feature.\n- Use a small code snippet only when it materially clarifies the concept.\n- No generic intro or conclusion.\n- Keep one topic roughly 180-300 words; if all 3 are selected keep the total under 750 words.\n- Keep bullets short enough for a terminal.\n- For file, command, or boundary lists, prefer compact aligned rows over paragraphs.\n- Avoid wide diagrams and Markdown tables.\n- Use plain file paths and command names without backticks unless a code snippet is necessary.\n- Do not modify files.\n- Output only the topic headings and the five requested sections.`;
}
