export function smartPrompt(task) {
  return `You are the tiny relevance classifier for 3Things, a coding micro-learning companion.\n\nDecide whether this coding task contains a worthwhile software-engineering learning opportunity.\n\nLaunch for meaningful implementation, debugging, architecture, framework behavior, tooling, testing, security, performance, data, API, deployment, or design-system tasks.\nSkip truly trivial work such as typo-only edits, mechanical renames, obvious text changes, or tiny formatting changes with no useful concept behind them.\n\nTASK:\n${task.prompt}\n\nBe conservative about skipping: if a useful concept can be taught from the task, launch. Keep reason under 12 words.`;
}

export function areasPrompt(task, config) {
  return `You power 3Things, a micro-learning companion for software developers.\n\nThe developer is doing this real task:\n${task.prompt}\n\nTheir configured learning interests are:\n${config.interests.join(', ') || '(none)'}\n\nReturn 3 to 6 learning-area options for this task. Prefer relevant configured interests. If suggestOutsideInterests=${config.suggestOutsideInterests}, add up to 2 highly relevant areas outside the configured list when they would teach something valuable.\n\nFor each option:\n- name: short category such as Backend, Frontend, Security, Architecture, DevOps, Databases, Testing, Performance, AI, Networking, Payments\n- source: "configured" if it matches a configured interest, otherwise "suggested"\n- reason: maximum 8 words, specific to this task\n\nDo not invent irrelevant areas just to fill the list.`;
}

export function topicsPrompt(task, area, historyTitles) {
  const learned = historyTitles.length ? historyTitles.join('; ') : '(none yet)';
  return `You power 3Things, which teaches exactly three compact concepts from a developer's current coding task.\n\nCURRENT TASK:\n${task.prompt}\n\nSELECTED LEARNING AREA: ${area}\n\nRECENTLY LEARNED TOPICS (avoid repeating unless this task adds a clearly deeper angle):\n${learned}\n\nReturn exactly 3 concepts that are directly connected to the task and useful beyond this one code change. Prefer mental models, engineering boundaries, failure modes, tradeoffs, protocol/framework mechanics, and production lessons over syntax trivia.\n\nEach item needs:\n- title: <= 6 words\n- why: <= 12 words, explaining why it matters here.`;
}

export function lessonPrompt(task, area, topics) {
  return `You are 3Things, a compact software-engineering teacher attached to real coding work.\n\nTASK THE DEVELOPER IS CURRENTLY DOING:\n${task.prompt}\n\nLEARNING AREA: ${area}\n\nTEACH THESE TOPICS:\n${topics.map((t, i) => `${i + 1}. ${t.title} — ${t.why}`).join('\n')}\n\nCreate a compact but complete lesson for the selected topic(s). This is micro-learning, not a blog post.\n\nFor EACH topic use exactly these sections:\n# <topic>\n**Mental model** — 2-4 short sentences.\n**How it works** — concise bullets or a tiny ASCII flow when useful.\n**In this task** — connect the knowledge concretely to the task above.\n**Common mistake** — one high-value failure mode.\n**Remember** — one memorable sentence.\n\nRules:\n- Prioritize understanding over code.\n- Use a small code snippet only when it materially clarifies the concept.\n- No generic intro or conclusion.\n- Keep one topic roughly 180-300 words; if all 3 are selected keep the total under 750 words.\n- Do not modify files.\n- Output Markdown only.`;
}
